server:
  port: 8076
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8075/eureka


spring:
    cloud:
       gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: DETAILS
              uri: lb://DETAILS
              predicates:
                - Path=/setup/details/**
            - id: LIST
              uri: lb://LIST
              predicates:
                - Path=/setup/list/**

# For actuator : url: http://localhost:8076/actuator/gateway/routes
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,info