server:
  port: 8076
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8075/eureka

spring:
    cloud:
       gateway:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true #this is for lowecase url of the services id registered in eureka
          routes: #This configurations we can also do in java class as created RouteConfig.java
            - id: DETAILS
              uri: lb://details 
              predicates: #http://localhost:8076/test/api/setup/details/users
                - Path=/test/api/setup/details/**
              filters:
                - RewritePath=/test/api(?<segment>.*), $\{segment}
            - id: LIST
              uri: lb://list
              predicates: #http://localhost:8076/setup/list/users
                - Path=/setup/list/**

# For actuator : url: http://localhost:8076/actuator/gateway/routes
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,info,health

